min_version = "2026.6.6"

[tools]
deno = "2.9.5"
hk = "1.55.0"
usage = "5.1.0"

[deps.aube]
auto = true

[settings]
experimental = true

[task_config]
includes = ["tasks", "home/.config/mise/tasks"]

[hooks]
postinstall = ["hk install --mise --quiet", "mise deps install"]

[shell_alias]
mr = 'mise run '
mi = 'mise install '

[env]
HK_MISE = "1"
HK_HIDE_WHEN_DONE = "true"
MISE_EXPERIMENTAL = "1"

_.path = ["{{config_root}}/node_modules/.bin"]
