shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.oh-my-zsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = [
  "clipboard.zsh",
  "compfix.zsh",
  "completion.zsh",
  "functions.zsh",
  "grep.zsh",
  "history.zsh",
  "key-bindings.zsh",
  "misc.zsh",
  "spectrum.zsh",
  "termsupport.zsh",
  "theme-and-appearance.zsh",
]

[plugins.omz-colored-man-pages]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/colored-man-pages"

[plugins.omz-command-not-found]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/command-not-found"

[plugins.omz-copyfile]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/copyfile"

[plugins.omz-copypath]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/copypath"

[plugins.omz-docker]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/docker"
profiles = ["docker", "macos-docker"]

[plugins.omz-docker-compose]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/docker-compose"
profiles = ["docker", "macos-docker"]

[plugins.omz-extract]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/extract"

[plugins.omz-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"

[plugins.omz-github]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/github"

[plugins.omz-gitignore]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/gitignore"

[plugins.omz-macos]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/macos"
profiles = ["macos", "macos-docker"]

[plugins.omz-man]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/man"

[plugins.omz-urltools]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/urltools"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "z-shell/F-Sy-H"
apply = ["defer"]

[plugins.zsh-brew-services]
github = "vasyharan/zsh-brew-services"
profiles = ["macos", "macos-docker"]

[plugins.zsh-completions]
github = "clarketm/zsh-completions"

[plugins.mac-zsh-completions]
github = "scriptingosx/mac-zsh-completions"
profiles = ["macos", "macos-docker"]

[plugins.jq-zsh-plugin]
github = "reegnz/jq-zsh-plugin"
